server:
  port: 2111
spring:
  application:
    name:simple-privider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root:INFO
    org.heibernate:INFO
    org.hibernate.type.descriptor.sql.BasicBinder:TRACE
    org.heibernate.type.descriptor.sql.BasicExtractor:Trace
